[0.000000] (-) TimerEvent: {}
[0.000937] (tcp_server_xml) JobQueued: {'identifier': 'tcp_server_xml', 'dependencies': OrderedDict()}
[0.001003] (tcp_server_xml) JobStarted: {'identifier': 'tcp_server_xml'}
[0.099237] (-) TimerEvent: {}
[0.199538] (-) TimerEvent: {}
[0.299824] (-) TimerEvent: {}
[0.400105] (-) TimerEvent: {}
[0.500384] (-) TimerEvent: {}
[0.600659] (-) TimerEvent: {}
[0.700942] (-) TimerEvent: {}
[0.801221] (-) TimerEvent: {}
[0.901505] (-) TimerEvent: {}
[0.998420] (tcp_server_xml) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 67, in execute\n    loop.run_until_complete(future)\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete\n    self.run_forever()\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever\n    self._run_once()\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once\n    event_list = self._selector.select(timeout)\n  File "/usr/lib/python3.10/selectors.py", line 469, in select\n    fd_event_list = self._selector.poll(timeout, max_ev)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 105, in build\n    return await extension.build(additional_hooks=additional_hooks)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 81, in build\n    available_commands = await self._get_available_commands(\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 171, in _get_available_commands\n    output = await check_output(\n  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 128, in check_output\n    assert not rc, f\'Expected {args} to pass: {stderr_data}\'\nAssertionError: Expected [\'/usr/bin/python3\', \'setup.py\', \'--help-commands\'] to pass: Traceback (most recent call last):\n  File "/home/klyx/git/p4/software_and_automation_frameworks_p4/mini_ws/src/tcp_server_xml/setup.py", line 5, in <module>\n    setup(\n  File "/home/klyx/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup\n    return distutils.core.setup(**attrs)\n  File "/usr/lib/python3.10/distutils/core.py", line 134, in setup\n    ok = dist.parse_command_line()\n  File "/usr/lib/python3.10/distutils/dist.py", line 480, in parse_command_line\n    if self.handle_display_options(option_order):\n  File "/home/klyx/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1123, in handle_display_options\n    return _Distribution.handle_display_options(self, option_order)\n  File "/usr/lib/python3.10/distutils/dist.py", line 683, in handle_display_options\n    self.print_commands()\n  File "/home/klyx/.local/lib/python3.10/site-packages/setuptools/dist.py", line 899, in print_commands\n    cmdclass = ep.resolve()\n  File "/home/klyx/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2471, in resolve\n    module = __import__(self.module_name, fromlist=[\'__name__\'], level=0)\n  File "/usr/lib/python3/dist-packages/nose/commands.py", line 89, in <module>\n    class nosetests(Command):\n  File "/usr/lib/python3/dist-packages/nose/commands.py", line 93, in nosetests\n    __parser = __config.getParser()\n  File "/usr/lib/python3/dist-packages/nose/config.py", line 590, in getParser\n    self.plugins.loadPlugins()\n  File "/usr/lib/python3/dist-packages/nose/plugins/manager.py", line 402, in loadPlugins\n    super(EntryPointPluginManager, self).loadPlugins()\n  File "/usr/lib/python3/dist-packages/nose/plugins/manager.py", line 412, in loadPlugins\n    from nose.plugins import builtin\n  File "/usr/lib/python3/dist-packages/nose/plugins/builtin.py", line 26, in <module>\n    plugmod = __import__(module, globals(), locals(), [cls])\n  File "/usr/lib/python3/dist-packages/nose/plugins/debug.py", line 7, in <module>\n    import pdb\n  File "/usr/lib/python3.10/pdb.py", line 77, in <module>\n    import code\n  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\n  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked\n  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked\n  File "<frozen importlib._bootstrap_external>", line 879, in exec_module\n  File "<frozen importlib._bootstrap_external>", line 964, in get_code\n  File "<frozen importlib._bootstrap_external>", line 448, in cache_from_source\n  File "<frozen importlib._bootstrap_external>", line 128, in _path_join\n  File "<frozen importlib._bootstrap_external>", line 128, in <listcomp>\nKeyboardInterrupt\n\n'}
[0.999031] (tcp_server_xml) JobEnded: {'identifier': 'tcp_server_xml', 'rc': 'SIGINT'}
[1.001569] (-) TimerEvent: {}
[1.009001] (-) EventReactorShutdown: {}
